version: '3.8'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: nextjs-app
    depends_on:
      - db  
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    env_file:
      - path: ./.env
        required: true
      - path: ./.env.local
        required: false

  db:
    container_name: postgres-db
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports: 
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres: