import LoginDialog from "@/components/dialogs/LoginDialog";
import Header from "@/components/global/Header";
import { Toaster } from "@/components/ui/sonner";
import CustomQueryClientProvider from "@/providers/query-client-provider";
import { ThemeProvider } from "@/providers/theme-provider";
import { WebContainerProvider } from "@/providers/web-container";
import type { Metadata } from "next";
import { SessionProvider } from "next-auth/react";
import { Geist, Geist_Mono, Roboto } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <CustomQueryClientProvider>
        <body className={`${roboto.className} antialiased`}>
          <SessionProvider>
            <WebContainerProvider>
              <ThemeProvider
                attribute="class"
                defaultTheme="system"
                enableSystem
                disableTransitionOnChange
              >
                <main className=" flex flex-col w-screen h-screen overflow-hidden   ">
                  <Header />
                  <div className=" min-h-0 grow">{children}</div>
                  <LoginDialog />
                  <Toaster />
                </main>
              </ThemeProvider>
            </WebContainerProvider>
          </SessionProvider>
        </body>
      </CustomQueryClientProvider>
    </html>
  );
}
